[package]
name = "dosomekamas"
version = "0.1.0"
description = "Assistant Forgemagie — Dofus 3.5"
authors = ["sorkin-dev"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "dosomekamas_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
xcap = "0.0.14"
image = { version = "0.25", default-features = false, features = ["png"] }
base64 = "0.22"
regex = "1"
rusty-tesseract = "1.1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

